---
- name:  Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Download wildfly tarball for jboss.org
  get_url:
    url: https://download.jboss.org/wildfly/13.0.0.Final/wildfly-13.0.0.Final.tar.gz
    dest: /tmp/wildfly-13.0.0.Final.tar.gz

- name: create wildfly group
  group:
    name: wildfly
    state: present

- name: create wildfly user
  user:
    group: wildfly
    name: wildfly
    state: present

- name: Delete wildfly directory
  file:
    path: /opt/wildfly
    state: absent
    group: wildfly

- name: Create a new wildfly directory
  file:
    path: /opt/wildfly
    state: directory
    group: wildfly

- name: Extract wildfly into wildfly directory
  unarchive:
    src: /tmp/wildfly-13.0.0.Final.tar.gz
    dest: /opt/wildfly
    extra_opts: ['--strip-components=1']
    copy: no
    group: wildfly

- name: Copy wildfly run script
  template:
    src: run.sh.j2
    dest: /opt/wildfly/bin/run.sh
    mode: 0755

- name: Copy wildfly service
  template:
    src: wildfly.service.j2
    dest: /usr/lib/systemd/system/wildfly.service
    mode: 0755

# notify start wildfly
- name: Restart wildfly
  service:
    name: wildfly
    state: started
    enabled: yes