---
- name:  Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Create wildfly group
  group:
    name: wildfly
    state: present

- name: Create wildfly user
  user:
    group: wildfly
    name: wildfly
    state: present

# - name: Delete wildfly directory
#   file:
#     path: /opt/wildfly
#     state: absent
#     group: wildfly

- name: Create wildfly directory
  file:
    path: /opt/wildfly
    state: directory
    group: wildfly
    owner: wildfly
  register: wildfly_exists

- name: Download wildfly tarball from jboss.org
  get_url:
    url: https://download.jboss.org/wildfly/13.0.0.Final/wildfly-13.0.0.Final.tar.gz
    dest: /tmp/wildfly-13.0.0.Final.tar.gz
  when: wildfly_exists.changed

- name: Extract wildfly into wildfly directory
  unarchive:
    src: /tmp/wildfly-13.0.0.Final.tar.gz
    dest: /opt/wildfly
    extra_opts: ['--strip-components=1']
    copy: no
    group: wildfly
    owner: wildfly
  when: wildfly_exists.changed

- name: Copy wildfly run script
  template:
    src: run.sh.j2
    dest: /opt/wildfly/bin/run.sh
    mode: 0755

- name: Copy wildfly service
  template:
    src: wildfly.service.j2
    dest: /usr/lib/systemd/system/wildfly.service
    mode: 0755

- name: Start wildfly
  service:
    name: wildfly
    state: started
    enabled: yes